#!/bin/bash

mkdir dependencies

cp -r /root/.m2/repository/fogbow/fogbow-as dependencies
cp -r /root/.m2/repository/fogbow/fogbow-ras dependencies
cp -r /root/.m2/repository/fogbow/fogbow-ms dependencies
cp -r /root/.m2/repository/fogbow/fogbow-accounting-service dependencies

sudo docker build --no-cache -t fogbow/finance-service:latest .
